### PR TITLE
fix(parser): fix some escape sequences in strings and indentation in block strings

### LINKED ISSUE #609: Block strings are parsed like non-block strings
## Description

Both in the lexer and in the `impl From<&'_ ast::StringValue> for String` conversion, block strings and "normal" string literals are treated the same except for the number of double-quote delimiters. Block strings should accept different escape sequences (only `\"""`), remove leading/trailing empty lines, and remove common indent.

https://spec.graphql.org/October2021/#sec-String-Value.Semantics

### Steps to reproduce

`crates/apollo-parser/src/ast/node_ext.rs`
```rust
#[cfg(test)]
mod tests {
    use crate::ast;
    use crate::Parser;

    #[test]
    fn test_block_string_1() {
        let input = r#"
            query ($arg: Int!) {
                field(
                    block_string: """
                          other\n\"""

                        \"text\" 
                    """
                )
            }
        "#;
        let values = extract_argument_values(input);
        let ast::Value::StringValue(block_string) = &values[0] else { panic!() };

        // Removed: common indent of non-empty lines, leading/trailing empty lines,
        // but not trailing space of a non-empty line
        // Unescaped: `\"""` only
        assert_eq!(
            String::try_from(block_string).as_deref(),
            Ok(r#"  other\n"""

\"text\" "#)
        );
    }

    #[test]
    fn test_block_string_2() {
        let input = r#"
            query ($arg: Int!) {
                field(
                    block_string: """\""""""
                )
            }
        "#;
        let values = extract_argument_values(input);
        let ast::Value::StringValue(block_string) = &values[0] else { panic!() };
        assert_eq!(String::try_from(block_string).as_deref(), Ok(r#"""""#));
    }

    fn extract_argument_values(input: &str) -> Vec<ast::Value> {
        let ast = Parser::new(input).parse();
        assert_eq!(ast.errors().as_slice(), []);
        let ast::Definition::OperationDefinition(operation) = ast
            .document()
            .definitions()
            .next()
            .unwrap()
        else { panic!("expected an operation") };
        let ast::Selection::Field(field) = operation
            .selection_set()
            .unwrap()
            .selections()
            .next()
            .unwrap()
        else { panic!("expected a field") };
        field
            .arguments()
            .unwrap()
            .arguments()
            .map(|arg| arg.value().unwrap())
            .collect()
    }
}
```

### Expected result

Tests pass

### Actual result

```
---- ast::node_ext::tests::test_block_string_2 stdout ----
thread 'ast::node_ext::tests::test_block_string_2' panicked at 'assertion failed: `(left == right)`
  left: `[ERROR@142:142 "expected R_PAREN, got EOF" EOF, ERROR@142:142 "expected R_CURLY, got EOF" EOF]`,
 right: `[]`', crates/apollo-parser/src/ast/node_ext.rs:333:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- ast::node_ext::tests::test_block_string_1 stdout ----
thread 'ast::node_ext::tests::test_block_string_1' panicked at 'assertion failed: `(left == right)`
  left: `Ok("\n                          other\n\"\"\"\n\n                        \"text\" \n                    ")`,
 right: `Ok("  other\\n\"\"\"\n\n\\\"text\\\" ")`', crates/apollo-parser/src/ast/node_ext.rs:309:9
```

### Environment

- `apollo-rs` crate: apollo-parser
- Crate version: current main, 126816fc6717bf5df429dac48cd71995e5538a7d

### LINKED ISSUE #611: Incorrect parsing of string with trailing \"
## Description

The conversion of `StringValue` to `String` is incorrect when the value ends with an escaped double-quote `\"`. There is likely a similar bug with block strings that end with `\"""` or starts with `"` but it is masked by https://github.com/apollographql/apollo-rs/issues/609. The offending code removes any number of `"` characters here:

https://github.com/apollographql/apollo-rs/blob/126816fc6717bf5df429dac48cd71995e5538a7d/crates/apollo-parser/src/ast/node_ext.rs#L201

### Steps to reproduce

`crates/apollo-parser/src/ast/node_ext.rs`
```rust
#[cfg(test)]
mod tests {
    use crate::ast;
    use crate::Parser;

    #[test]
    fn test_tailing_escaped_quote() {
        let input = r#"
            query ($arg: Int!) {
                field(
                    string: "a\""
                )
            }
        "#;
        let values = extract_argument_values(input);
        let ast::Value::StringValue(block_string) = &values[0] else { panic!() };
        assert_eq!(String::try_from(block_string).as_deref(), Ok(r#"a""#));
    }

    fn extract_argument_values(input: &str) -> Vec<ast::Value> {
        let ast = Parser::new(input).parse();
        assert_eq!(ast.errors().as_slice(), []);
        let ast::Definition::OperationDefinition(operation) = ast
            .document()
            .definitions()
            .next()
            .unwrap()
        else { panic!("expected an operation") };
        let ast::Selection::Field(field) = operation
            .selection_set()
            .unwrap()
            .selections()
            .next()
            .unwrap()
        else { panic!("expected a field") };
        field
            .arguments()
            .unwrap()
            .arguments()
            .map(|arg| arg.value().unwrap())
            .collect()
    }
}
```

### Expected result

Test passes

### Actual result

```rust
thread 'ast::node_ext::tests::test_tailing_escaped_quote' panicked at 'assertion failed: `(left == right)`
  left: `Ok("a\\")`,
 right: `Ok("a\"")`', crates/apollo-parser/src/ast/node_ext.rs:301:9
```

### Environment

- `apollo-rs` crate: apollo-parser
- Crate version: either 0.5.3 or `main` 126816fc6717bf5df429dac48cd71995e5538a7d

### PR DESCRIPTION
**Pull request by goto-bus-stop**
Follow-up to #638, fixing conversion of StringValue nodes to Rust strings.

Fixes #609
Fixes #611

 This handles
- [x] escape sequences in single-quoted strings and
- [x] indentation in block strings #609
- [x] wrong behaviours when a string ends with an escaped `"` #611 

This does not handle these unicode escape issues:
- https://github.com/apollographql/apollo-rs/issues/608
- https://github.com/apollographql/apollo-rs/issues/640

### CODE REVIEW

File: crates/apollo-parser/src/ast/node_ext.rs [hunk 1]
```diff
@@ -193,12 +196,164 @@ fn unescape_string(input: &str) -> String {
...
+        let Some(index) = memchr::memchr2(b'\r', b'\n', self.input.as_bytes()) else {
+            self.finished = true;
+            return Some(self.input);
+        };
+        let line = &self.input[..index];
+        let rest = match self.input.get(index..=index + 1) {
+            Some("\r\n") => &self.input[index + 2..],
+            _ => &self.input[index + 1..],
+        };
+        self.input = rest;
```
Comment (SimonSapin) [inline crates/apollo-parser/src/ast/node_ext.rs:240]: The above is fine. It can be marginally nicer with `split_at` and `strip_prefix`:
```suggestion
        let (line, rest) = self.input.split_at(index);
        // `rest` starts with \r or \n
        self.input = rest.strip_prefix("\r\n").unwrap_or_else(|| &rest[1..])
```

File: crates/apollo-parser/src/ast/node_ext.rs [hunk 2]
```diff
@@ -193,12 +196,164 @@ fn unescape_string(input: &str) -> String {
...
+        line.chars().take_while(|&c| is_whitespace(c)).count()
+    }
+
+    // 3. For each line in lines:
+    let common_indent = split_lines(raw_value)
+        // 3.a. If line is the first item in lines, continue to the next line.
+        .skip(1)
+        .filter_map(|line| {
+            // 3.b. Let length be the number of characters in line.
+            let length = line.len();
```
Comment (SimonSapin) [inline crates/apollo-parser/src/ast/node_ext.rs:290]: Please add a comment to explain that while `str.len()` counts UTF-8 bytes and `count_indent` counts `char`s, comparing them is still ok because the WhiteSpace characters we’re looking for are in the ASCII range and so occupy one UTF-8 byte each.

File: crates/apollo-parser/src/ast/node_ext.rs [hunk 3]
```diff
@@ -193,12 +196,164 @@ fn unescape_string(input: &str) -> String {
...
+                // 4.a.ii. Remove commonIndent characters from the beginning of line.
+                &line[common_indent.min(line.len())..]
+            }
+        })
+        // 5. While the first item line in lines contains only WhiteSpace:
+        // 5.a. Remove the first item from lines.
+        .skip_while(|line| is_whitespace_line(line));
+
+    // 7. Let formatted be the empty character sequence.
+    let mut formatted = String::with_capacity(raw_value.len());
```
Comment (SimonSapin) [inline crates/apollo-parser/src/ast/node_ext.rs:316]: Please add a comment to say step 6 is handled below

File: crates/apollo-parser/src/ast/node_ext.rs [hunk 4]
```diff
@@ -281,3 +436,133 @@ fn text_of_first_token(node: &SyntaxNode) -> TokenText {
...
+        assert_eq!(unescape_string(r#"quote \""#), "quote \"");
+        assert_eq!(
+            unescape_string(r"escaped \n\r\b\t\f"),
+            "escaped \n\r\u{0008}\t\u{000c}"
+        );
+        assert_eq!(unescape_string(r"slashes \\ \/"), r"slashes \ /");
+        assert_eq!(
+            unescape_string("unescaped unicode outside BMP \u{1f600}"),
+            "unescaped unicode outside BMP \u{1f600}"
+        );
```
Comment (SimonSapin) [inline crates/apollo-parser/src/ast/node_ext.rs:461]: This test case is misleading. It looks like it’s testing for https://github.com/apollographql/apollo-rs/issues/640 but that’s not implemented yet. The test passes because the Rust input string is not a raw string so `\u{1f600}` is unescaped by the Rust parser and `unescape_string` doesn’t end up unescaping anything in this case.

File: crates/apollo-parser/src/ast/node_ext.rs [hunk 5]
```diff
@@ -281,3 +436,133 @@ fn text_of_first_token(node: &SyntaxNode) -> TokenText {
...
+    fn it_does_not_unescape_block_strings() {
+        assert_eq!(
+            unescape_block_string(r"escaped \n\r\b\t\f"),
+            r"escaped \n\r\b\t\f"
+        );
+        assert_eq!(unescape_block_string(r"slashes \\ \/"), r"slashes \\ \/");
+        assert_eq!(
+            unescape_block_string("unescaped unicode outside BMP \u{1f600}"),
+            "unescaped unicode outside BMP \u{1f600}"
+        );
```
Comment (SimonSapin) [inline crates/apollo-parser/src/ast/node_ext.rs:530]: Same as previous comment

**Review by SimonSapin — APPROVED** [review]
Looks great!

File: crates/apollo-parser/src/parser/grammar/value.rs [hunk 6]
```diff
@@ -186,6 +186,48 @@ enum Test @dir__one(string: "string value", int_value: -10, float_value: -1.123e
         }
     }
 
+    #[test]
```
Comment (lrlna) [inline crates/apollo-parser/src/parser/grammar/value.rs:189]: Should we add these to the test_data dir? or are these better addressed here?

**Review by lrlna — APPROVED** [review]
\o/

File: crates/apollo-parser/src/ast/node_ext.rs (hunk 5 above)
Comment (goto-bus-stop) [reply crates/apollo-parser/src/ast/node_ext.rs:530]: Right, these are meant to test literal non-escaped unicode characters in the string, I'll add a comment to clarify.

File: crates/apollo-parser/src/parser/grammar/value.rs (hunk 6 above)
Comment (goto-bus-stop) [reply crates/apollo-parser/src/parser/grammar/value.rs:189]: `test_data` only checks the AST/CST resulting from parsing, it doesn't check the conversion from CST StringValue to String.

File: crates/apollo-parser/src/ast/node_ext.rs (hunk 5 above)
Comment (SimonSapin) [reply crates/apollo-parser/src/ast/node_ext.rs:530]: Perhaps use non-escaped rust syntax? Like 그라프큐엘 in the expected result of another test

File: crates/apollo-parser/src/ast/node_ext.rs (hunk 1 above)
Comment (goto-bus-stop) [reply crates/apollo-parser/src/ast/node_ext.rs:240]: my personal feeling is that `split_at` looks nicer but the manual `match` is more obviously correct despite being a bit noisy... though as i look back and forth i don't feel strongly anymore.
