### PR TITLE
fix(compiler): use #[salsa::transparent] for all find_ queries

### LINKED ISSUE #373: use #[salsa::transparent] for db.find_ derived queries
It's nice to have the db.find_ queries as part of the same db API, but these don't really need to be cached, so we can attach the `#[salsa::transparent]` attribute to them.

### PR DESCRIPTION
**Pull request by lrlna**
We don't need to store these queries in salsa's cache, so annotate them with `#[salsa::transparent]` and compute them when necessary.

Closes #373

### CODE REVIEW

File: crates/apollo-compiler/src/database/hir_db.rs [hunk 1]
```diff
@@ -34,75 +35,172 @@ pub trait HirDatabase: InputDatabase + AstDatabase {
...
+    /// interface InterfaceType implements Baz { me: String }
+    /// ```
+    /// we can say that:
+    ///
+    /// - `Foo` and `Bar` are a subtypes of `UnionType`.
+    /// - `ObjectType` and `InterfaceType` are subtypes of `Baz`.
     fn subtype_map(&self) -> Arc<HashMap<String, HashSet<String>>>;
 
+    /// Return `true` if the provided `abstract_type` is a subtype of the
+    /// corresponding `maybe_subtype`.
```
Comment (SimonSapin) [inline crates/apollo-compiler/src/database/hir_db.rs:176]: This sentence seems backwards?

```suggestion
    /// Return `true` if the provided `maybe_subtype` is a subtype of the
    /// corresponding `abstract_type`.
```

**Review by SimonSapin — APPROVED** [review]

File: crates/apollo-compiler/src/database/hir_db.rs [hunk 2]
```diff
@@ -34,75 +35,172 @@ pub trait HirDatabase: InputDatabase + AstDatabase {
...
     fn directive_definitions(&self) -> ByName<DirectiveDefinition>;
 
+    /// Return all input object type definitions defined in the compiler.
     fn input_objects(&self) -> ByName<InputObjectTypeDefinition>;
 
     // Derived from above queries:
-
+    /// Return an operation definition corresponding to the name and file id.
+    /// Result of this query is not cached internally.
+    #[salsa::transparent]
```
Comment (goto-bus-stop) [inline crates/apollo-compiler/src/database/hir_db.rs:65]: @SimonSapin brought up that this is still scanning a Vec internally: https://apollograph.slack.com/archives/C02H6SKKP6Y/p1672929069207239

so we could keep this cached for now?

Comment (lrlna) [reply crates/apollo-compiler/src/database/hir_db.rs]: yea sounds good!

**Review by goto-bus-stop — APPROVED** [review]
